version: 2
jobs:
  Tests:
    docker:
      - image: circleci/golang:1.15

      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/Pavel7004/PSR
    steps:
      - checkout

      - run:
          name: Fetch the dependenses
          command: go mod tidy

      - run:
          name: Run tests
          command: go test -race -cover -coverprofile coverage.out ./...
